---
include:
  - board: nice_nano
    shield: corne_left
  - board: nice_nano
    shield: corne_right
  - board: nice_nano
    shield: corne_left
    cmake-args: -DSHIELD=nice_view_adapter -DSHIELD=nice_view
  - board: nice_nano
    shield: corne_right
    cmake-args: -DSHIELD=nice_view_adapter -DSHIELD=nice_view
